sudo: false

language: python

cache:
  directories:
  - $HOME/anaconda/pkgs

matrix:
    fast_finish: true
    include:
    #- python: 2.7
      #env:
      #- PYTHON_VERSION=2.7
      #- NUMPY_VERSION=1.7
      #- JOB_NAME: "python_27_numpy_17"

    #- python: 2.7
      #env:
      #- PYTHON_VERSION=2.7
      #- NUMPY_VERSION=1.8
      #- JOB_NAME: "python_27_numpy_18"

    #- python: 2.7
      #env:
      #- PYTHON_VERSION=3.4
      #- NUMPY_VERSION=1.7
      #- JOB_NAME: "python_34_numpy_17"
    - python: 2.7
      env:
      - PYTHON_VERSION=3.4
      - NUMPY_VERSION=1.9
      - JOB_NAME: "python_34_numpy_19"

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - conda update --yes conda

  # Fix for headless TravisCI
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - conda create -n testenv python=$PYTHON_VERSION numpy=$NUMPY_VERSION cython pytest setuptools
  - source activate testenv

script:
  - python setup.py test
  - python setup.py install
